### ISSUE TITLE
Does not contain password validation enabled by default

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/angular-workflows#140]
#### Describe the bug
on the change password screen, the validation "does not contain password" is enabled 
#### What are the steps to reproduce?
1. Login and then select change password.
2. does not contain password is enabled

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/170492896-afb9d5aa-9c0a-4670-91ff-ba9b167e1429.png)

**Comment by ektasawant** [comment]
This is just an example in demo app, not in default validations.
