### ISSUE TITLE
Example project, gets 404 when a user tries to log out

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-workflows#160]
#### What are the steps to reproduce?
1. Go to example project
2. Log in
3. Log out
4. Check console

#### Screenshots or links to minimum reproduction example
http://localhost:4200/undefined
![Screen Shot 2022-08-26 at 10 45 47 AM](https://user-images.githubusercontent.com/8997218/186931209-22c415a3-8553-4c99-b972-07c2dc421554.png)

#### Environment
Mac Chrome

**Comment by ektasawant** [comment]
Duplicate issue https://github.com/brightlayer-ui/angular-workflows/issues/71
